//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackagePlanner.ERPCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", ConfigurationName="ERPCustomer.Customers_Port")]
    public interface Customers_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackagePlanner.ERPCustomer.Read_Result Read(PackagePlanner.ERPCustomer.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.Read_Result> ReadAsync(PackagePlanner.ERPCustomer.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackagePlanner.ERPCustomer.ReadByRecId_Result ReadByRecId(PackagePlanner.ERPCustomer.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadByRecId_Result> ReadByRecIdAsync(PackagePlanner.ERPCustomer.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackagePlanner.ERPCustomer.ReadMultiple_Result ReadMultiple(PackagePlanner.ERPCustomer.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadMultiple_Result> ReadMultipleAsync(PackagePlanner.ERPCustomer.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackagePlanner.ERPCustomer.IsUpdated_Result IsUpdated(PackagePlanner.ERPCustomer.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.IsUpdated_Result> IsUpdatedAsync(PackagePlanner.ERPCustomer.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackagePlanner.ERPCustomer.GetRecIdFromKey_Result GetRecIdFromKey(PackagePlanner.ERPCustomer.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customers:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(PackagePlanner.ERPCustomer.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public partial class Customers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string responsibility_CenterField;
        
        private string location_CodeField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string iC_Partner_CodeField;
        
        private string contactField;
        
        private string salesperson_CodeField;
        
        private string customer_Posting_GroupField;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string customer_Price_GroupField;
        
        private string customer_Disc_GroupField;
        
        private string payment_Terms_CodeField;
        
        private string reminder_Terms_CodeField;
        
        private string fin_Charge_Terms_CodeField;
        
        private string currency_CodeField;
        
        private string language_CodeField;
        
        private string search_NameField;
        
        private decimal credit_Limit_LCYField;
        
        private bool credit_Limit_LCYFieldSpecified;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private Application_Method application_MethodField;
        
        private bool application_MethodFieldSpecified;
        
        private bool combine_ShipmentsField;
        
        private bool combine_ShipmentsFieldSpecified;
        
        private Reserve reserveField;
        
        private bool reserveFieldSpecified;
        
        private Shipping_Advice shipping_AdviceField;
        
        private bool shipping_AdviceFieldSpecified;
        
        private string shipping_Agent_CodeField;
        
        private string base_Calendar_CodeField;
        
        private decimal balance_LCYField;
        
        private bool balance_LCYFieldSpecified;
        
        private decimal balance_Due_LCYField;
        
        private bool balance_Due_LCYFieldSpecified;
        
        private decimal sales_LCYField;
        
        private bool sales_LCYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
                this.RaisePropertyChanged("Responsibility_Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
                this.RaisePropertyChanged("Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
                this.RaisePropertyChanged("Phone_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
                this.RaisePropertyChanged("IC_Partner_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
                this.RaisePropertyChanged("Salesperson_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Customer_Posting_Group {
            get {
                return this.customer_Posting_GroupField;
            }
            set {
                this.customer_Posting_GroupField = value;
                this.RaisePropertyChanged("Customer_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("Gen_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("VAT_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Customer_Price_Group {
            get {
                return this.customer_Price_GroupField;
            }
            set {
                this.customer_Price_GroupField = value;
                this.RaisePropertyChanged("Customer_Price_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Customer_Disc_Group {
            get {
                return this.customer_Disc_GroupField;
            }
            set {
                this.customer_Disc_GroupField = value;
                this.RaisePropertyChanged("Customer_Disc_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
                this.RaisePropertyChanged("Payment_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Reminder_Terms_Code {
            get {
                return this.reminder_Terms_CodeField;
            }
            set {
                this.reminder_Terms_CodeField = value;
                this.RaisePropertyChanged("Reminder_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Fin_Charge_Terms_Code {
            get {
                return this.fin_Charge_Terms_CodeField;
            }
            set {
                this.fin_Charge_Terms_CodeField = value;
                this.RaisePropertyChanged("Fin_Charge_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
                this.RaisePropertyChanged("Currency_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Language_Code {
            get {
                return this.language_CodeField;
            }
            set {
                this.language_CodeField = value;
                this.RaisePropertyChanged("Language_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
                this.RaisePropertyChanged("Search_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Credit_Limit_LCY {
            get {
                return this.credit_Limit_LCYField;
            }
            set {
                this.credit_Limit_LCYField = value;
                this.RaisePropertyChanged("Credit_Limit_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_Limit_LCYSpecified {
            get {
                return this.credit_Limit_LCYFieldSpecified;
            }
            set {
                this.credit_Limit_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Credit_Limit_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public Blocked Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
                this.RaisePropertyChanged("BlockedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=24)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
                this.RaisePropertyChanged("Last_Date_Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_ModifiedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public Application_Method Application_Method {
            get {
                return this.application_MethodField;
            }
            set {
                this.application_MethodField = value;
                this.RaisePropertyChanged("Application_Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_MethodSpecified {
            get {
                return this.application_MethodFieldSpecified;
            }
            set {
                this.application_MethodFieldSpecified = value;
                this.RaisePropertyChanged("Application_MethodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool Combine_Shipments {
            get {
                return this.combine_ShipmentsField;
            }
            set {
                this.combine_ShipmentsField = value;
                this.RaisePropertyChanged("Combine_Shipments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Combine_ShipmentsSpecified {
            get {
                return this.combine_ShipmentsFieldSpecified;
            }
            set {
                this.combine_ShipmentsFieldSpecified = value;
                this.RaisePropertyChanged("Combine_ShipmentsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public Reserve Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
                this.RaisePropertyChanged("Reserve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReserveSpecified {
            get {
                return this.reserveFieldSpecified;
            }
            set {
                this.reserveFieldSpecified = value;
                this.RaisePropertyChanged("ReserveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public Shipping_Advice Shipping_Advice {
            get {
                return this.shipping_AdviceField;
            }
            set {
                this.shipping_AdviceField = value;
                this.RaisePropertyChanged("Shipping_Advice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipping_AdviceSpecified {
            get {
                return this.shipping_AdviceFieldSpecified;
            }
            set {
                this.shipping_AdviceFieldSpecified = value;
                this.RaisePropertyChanged("Shipping_AdviceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
                this.RaisePropertyChanged("Base_Calendar_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal Balance_LCY {
            get {
                return this.balance_LCYField;
            }
            set {
                this.balance_LCYField = value;
                this.RaisePropertyChanged("Balance_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_LCYSpecified {
            get {
                return this.balance_LCYFieldSpecified;
            }
            set {
                this.balance_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Balance_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal Balance_Due_LCY {
            get {
                return this.balance_Due_LCYField;
            }
            set {
                this.balance_Due_LCYField = value;
                this.RaisePropertyChanged("Balance_Due_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_Due_LCYSpecified {
            get {
                return this.balance_Due_LCYFieldSpecified;
            }
            set {
                this.balance_Due_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Balance_Due_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal Sales_LCY {
            get {
                return this.sales_LCYField;
            }
            set {
                this.sales_LCYField = value;
                this.RaisePropertyChanged("Sales_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sales_LCYSpecified {
            get {
                return this.sales_LCYFieldSpecified;
            }
            set {
                this.sales_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Sales_LCYSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public enum Blocked {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Ship,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public enum Application_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Apply_to_Oldest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public enum Reserve {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Always,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public enum Shipping_Advice {
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Complete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public partial class Customers_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Customers_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Customers_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers")]
    public enum Customers_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Customer_Posting_Group,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Customer_Price_Group,
        
        /// <remarks/>
        Customer_Disc_Group,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Reminder_Terms_Code,
        
        /// <remarks/>
        Fin_Charge_Terms_Code,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Credit_Limit_LCY,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Application_Method,
        
        /// <remarks/>
        Combine_Shipments,
        
        /// <remarks/>
        Reserve,
        
        /// <remarks/>
        Shipping_Advice,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Base_Calendar_Code,
        
        /// <remarks/>
        Balance_LCY,
        
        /// <remarks/>
        Balance_Due_LCY,
        
        /// <remarks/>
        Sales_LCY,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public PackagePlanner.ERPCustomer.Customers Customers;
        
        public Read_Result() {
        }
        
        public Read_Result(PackagePlanner.ERPCustomer.Customers Customers) {
            this.Customers = Customers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public PackagePlanner.ERPCustomer.Customers Customers;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(PackagePlanner.ERPCustomer.Customers Customers) {
            this.Customers = Customers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public PackagePlanner.ERPCustomer.Customers_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(PackagePlanner.ERPCustomer.Customers_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PackagePlanner.ERPCustomer.Customers[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(PackagePlanner.ERPCustomer.Customers[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customers", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/customers", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Customers_PortChannel : PackagePlanner.ERPCustomer.Customers_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Customers_PortClient : System.ServiceModel.ClientBase<PackagePlanner.ERPCustomer.Customers_Port>, PackagePlanner.ERPCustomer.Customers_Port {
        
        public Customers_PortClient() {
        }
        
        public Customers_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Customers_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customers_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customers_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PackagePlanner.ERPCustomer.Read_Result PackagePlanner.ERPCustomer.Customers_Port.Read(PackagePlanner.ERPCustomer.Read request) {
            return base.Channel.Read(request);
        }
        
        public PackagePlanner.ERPCustomer.Customers Read(string No) {
            PackagePlanner.ERPCustomer.Read inValue = new PackagePlanner.ERPCustomer.Read();
            inValue.No = No;
            PackagePlanner.ERPCustomer.Read_Result retVal = ((PackagePlanner.ERPCustomer.Customers_Port)(this)).Read(inValue);
            return retVal.Customers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.Read_Result> PackagePlanner.ERPCustomer.Customers_Port.ReadAsync(PackagePlanner.ERPCustomer.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.Read_Result> ReadAsync(string No) {
            PackagePlanner.ERPCustomer.Read inValue = new PackagePlanner.ERPCustomer.Read();
            inValue.No = No;
            return ((PackagePlanner.ERPCustomer.Customers_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PackagePlanner.ERPCustomer.ReadByRecId_Result PackagePlanner.ERPCustomer.Customers_Port.ReadByRecId(PackagePlanner.ERPCustomer.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public PackagePlanner.ERPCustomer.Customers ReadByRecId(string recId) {
            PackagePlanner.ERPCustomer.ReadByRecId inValue = new PackagePlanner.ERPCustomer.ReadByRecId();
            inValue.recId = recId;
            PackagePlanner.ERPCustomer.ReadByRecId_Result retVal = ((PackagePlanner.ERPCustomer.Customers_Port)(this)).ReadByRecId(inValue);
            return retVal.Customers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadByRecId_Result> PackagePlanner.ERPCustomer.Customers_Port.ReadByRecIdAsync(PackagePlanner.ERPCustomer.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            PackagePlanner.ERPCustomer.ReadByRecId inValue = new PackagePlanner.ERPCustomer.ReadByRecId();
            inValue.recId = recId;
            return ((PackagePlanner.ERPCustomer.Customers_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PackagePlanner.ERPCustomer.ReadMultiple_Result PackagePlanner.ERPCustomer.Customers_Port.ReadMultiple(PackagePlanner.ERPCustomer.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public PackagePlanner.ERPCustomer.Customers[] ReadMultiple(PackagePlanner.ERPCustomer.Customers_Filter[] filter, string bookmarkKey, int setSize) {
            PackagePlanner.ERPCustomer.ReadMultiple inValue = new PackagePlanner.ERPCustomer.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            PackagePlanner.ERPCustomer.ReadMultiple_Result retVal = ((PackagePlanner.ERPCustomer.Customers_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadMultiple_Result> PackagePlanner.ERPCustomer.Customers_Port.ReadMultipleAsync(PackagePlanner.ERPCustomer.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.ReadMultiple_Result> ReadMultipleAsync(PackagePlanner.ERPCustomer.Customers_Filter[] filter, string bookmarkKey, int setSize) {
            PackagePlanner.ERPCustomer.ReadMultiple inValue = new PackagePlanner.ERPCustomer.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((PackagePlanner.ERPCustomer.Customers_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PackagePlanner.ERPCustomer.IsUpdated_Result PackagePlanner.ERPCustomer.Customers_Port.IsUpdated(PackagePlanner.ERPCustomer.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            PackagePlanner.ERPCustomer.IsUpdated inValue = new PackagePlanner.ERPCustomer.IsUpdated();
            inValue.Key = Key;
            PackagePlanner.ERPCustomer.IsUpdated_Result retVal = ((PackagePlanner.ERPCustomer.Customers_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.IsUpdated_Result> PackagePlanner.ERPCustomer.Customers_Port.IsUpdatedAsync(PackagePlanner.ERPCustomer.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.IsUpdated_Result> IsUpdatedAsync(string Key) {
            PackagePlanner.ERPCustomer.IsUpdated inValue = new PackagePlanner.ERPCustomer.IsUpdated();
            inValue.Key = Key;
            return ((PackagePlanner.ERPCustomer.Customers_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PackagePlanner.ERPCustomer.GetRecIdFromKey_Result PackagePlanner.ERPCustomer.Customers_Port.GetRecIdFromKey(PackagePlanner.ERPCustomer.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            PackagePlanner.ERPCustomer.GetRecIdFromKey inValue = new PackagePlanner.ERPCustomer.GetRecIdFromKey();
            inValue.Key = Key;
            PackagePlanner.ERPCustomer.GetRecIdFromKey_Result retVal = ((PackagePlanner.ERPCustomer.Customers_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.GetRecIdFromKey_Result> PackagePlanner.ERPCustomer.Customers_Port.GetRecIdFromKeyAsync(PackagePlanner.ERPCustomer.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<PackagePlanner.ERPCustomer.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            PackagePlanner.ERPCustomer.GetRecIdFromKey inValue = new PackagePlanner.ERPCustomer.GetRecIdFromKey();
            inValue.Key = Key;
            return ((PackagePlanner.ERPCustomer.Customers_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
